options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: python:3.11
    entrypoint: bash
    dir: dbt_project
    env:
      - DBT_PROFILES_DIR=/workspace
    args:
      - -c
      - |
        set -e
        pip install --upgrade pip
        pip install dbt-bigquery
        dbt debug
        dbt run
        dbt test
        dbt docs generate


  - name: gcr.io/cloud-builders/gsutil
    args:
      - -m
      - rsync
      - -r
      - -d
      - dbt_project/target
      - gs://dbt-docs-site

        
timeout: "1200s"







