options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: python:3.11
    entrypoint: bash
    env:
      - DBT_PROFILES_DIR=/workspace
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install dbt-bigquery
        dbt debug
        dbt run
        dbt test

timeout: "1200s"

